# Generated by Django 5.0.7 on 2024-07-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField(max_length=4)),
                ('summary', models.CharField(max_length=250)),
                ('poster', models.CharField(max_length=250)),
            ],
        ),
    ]
